query FilmDAuteurs {
	films: Films_d_auteur(sort: "-numero", filter: { video: { id: { _nnull: true } } }) {
		id
		lien_video
		titre_original
		titre_english
		slug
		date_created
		video {
			height
			html
			thumbnail_url
			width
			thumbnail_width
			thumbnail_height
		}
		ville
		voix
		synopsis_fr
		synopsis_en
		son
		scenario
		realisation
		public
		production
		prix_obtenus_par_le_film
		participants
		numero
		musique
		mot_de_passe
		montage
		logo {
			id
		}
		image_1 {
			id
		}
		image_2 {
			id
		}
		image_3 {
			id
		}
		lien_bande_annonce
		langue_originale
		in_progress
		image
		format
		duree_secondes
		duree_minutes
		coproduction
		contact
		annee
		animation
		affiche {
			id
		}
	}
}
