query FilmDAuteurs {
	films: Films_d_auteur(sort: "-numero") {
		id
		lien_video
		titre_original
		titre_english
		slug
		date_created
		video {
			height
			html
			thumbnail_url
			width
			thumbnail_width
			thumbnail_height
		}
		ville
		voix
		synopsis_fr
		synopsis_en
		son
		scenario
		realisation
		public
		production
		prix_obtenus_par_le_film
		participants
		numero
		musique
		mot_de_passe
		montage
		logo {
			id
		}
		image_1 {
			id
			title
		}
		image_2 {
			id
			title
		}
		image_3 {
			id
			title
		}
		lien_bande_annonce
		langue_originale
		in_progress
		image
		format
		duree_secondes
		duree_minutes
		coproduction
		contact
		annee
		animation
		affiche {
			id
			title
		}
	}
	latests: Films_d_auteur(
		sort: "-numero"
		filter: {
			_and: [
				{ video: { id: { _nnull: true } } }
				{ in_progress: { _eq: false } }
				{ lien_video: { _nnull: true } }
			]
			mot_de_passe: { _empty: true }
		}
	) {
		slug
	}
}
