query FilmDAuteurs {
	films: Films_d_auteur(sort: "-numero") {
		id
		lien_video
		titre_original
		titre_english
		slug
		date_created
		video {
			height
			html
			thumbnail_url
			width
			thumbnail_width
			thumbnail_height
		}
		ville
		voix
		synopsis_fr
		synopsis_en
		son
		scenario
		realisation
		public
		production
		participants
		numero
		musique
		mot_de_passe
		montage
		logo {
			id
		}
		image_1 {
			id
			title
		}
		image_2 {
			id
			title
		}
		image_3 {
			id
			title
		}
		image_de_remplacement {
			id
			title
		}
		lien_bande_annonce
		video_bande_annonce {
			height
			html
			thumbnail_url
			width
			thumbnail_width
			thumbnail_height
		}
		langue_originale
		in_progress
		image
		format
		duree_secondes
		duree_minutes
		coproduction
		contact
		annee
		animation
		affiche {
			id
			title
		}
	}
	latests: Films_d_auteur(
		sort: "-numero"
		filter: {
			in_progress: { _eq: false }
		}
	) {
		slug
	}
	awards: Prix(sort: "-numero", limit: -1) {
		description
		numero
		film_awarded {
			item {
				... on Films_d_auteur {
					id
				}
			}
		}
	}
}
