query PrixQuery {
	prix: Prix(limit: -1) {
		numero
		description
		film_awarded {
			item {
				... on Films_d_auteur {
					__typename
					id
					logo {
						id
					}
					title: titre_original
					slug
				}
				... on films_d_ateliers {
					__typename
					id
					logo {
						id
					}
					title: titre
					slug
				}
				... on films_de_commande {
					__typename
					id
					logo {
						id
					}
					title: titre
					slug
				}
				... on series {
					__typename
					id
					logo {
						id
					}
					title: titre
					slug
				}
				... on episodes {
					__typename
					id
					logo {
						id
					}
					title: titre
					slug
				}
			}
		}
	}
}
