query SeriesPage {
	series {
		date_created
		id
		image_remplacement {
			id
		}
		logo {
			id
		}
		numero
		realisation
		synopsis_en
		synopsis_fr
		titre
		titre_english
		video_bande_annonce {
			html
			thumbnail_url
			width
			thumbnail_width
			thumbnail_height
			height
		}
		episodes {
			annee
			coproduction
			date_created
			duree_minutes
			duree_secondes
			id
			logo {
				id
			}
			numero
			realisation
			synopsis_en
			synopsis_fr
			titre
			titre_english
			video {
				id
				html
				height
				width
				thumbnail_width
				thumbnail_url
				thumbnail_height
			}
		}
	}
}
