query FilmDAteliers {
	films: films_d_ateliers(sort: "-numero", filter: { video: { id: { _nnull: true } } }) {
		id
		annee
		date_created
		duree_secondes
		duree_minutes
		logo {
			id
		}
		numero
		online
		partenariats
		public
		synopsis_fr
		technique
		titre
		slug
		user_created
		video {
			html
			height
			thumbnail_height
			thumbnail_url
			thumbnail_width
			video_id
			width
		}
	}
}
